title: Steven Roberts
email: steven94@vt.edu
author: Steven Roberts
description: The personal website of Steven Roberts where you can find my publications, presentations, CV, and contact information

extra-menu-items:
  - title: Curriculum Vitae
    priority: 50
    icon: insert_drive_file
    url: /assets/doc/cv.pdf

links:
  Github: https://github.com/Steven-Roberts
  Google Scholar: https://scholar.google.com/citations?user=C4Y4pMIAAAAJ
  ORCID: https://orcid.org/0000-0002-7225-2501
  Mendeley: https://www.mendeley.com/profiles/steven-roberts6
  Scopus: https://www.scopus.com/authid/detail.uri?authorId=57208689731
  Stack Overflow: https://stackoverflow.com/users/2605245
  Facebook: https://www.facebook.com/steven.byram.roberts
  Chess.com: https://www.chess.com/member/steven-roberts

permalink: pretty

plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
    style: compressed
