title: Steven Roberts
email: steven94@vt.edu

extra-menu-items:
    - title: Curriculum Vitae
      priority: 50
      icon: insert_drive_file
      url: /assets/doc/cv.pdf
      badge: Updated

links:
    Github: https://github.com/Steven-Roberts
    Google Scholar: https://scholar.google.com/citations?user=C4Y4pMIAAAAJ
    Stack Overflow: https://stackoverflow.com/u/2605245s

permalink: pretty

plugins:
    - jekyll-github-metadata
    - jekyll-sitemap
    - jekyll-seo-tag

sass:
    style: compressed
