title: Steven Roberts
email:
    username: steven94
    domain: vt.edu

permalink: pretty

plugins:
    - jekyll-github-metadata
    - jekyll-sitemap
    - jekyll-seo-tag

sass:
    style: compressed

exclude:
    - Gemfile
    - LICENSE.md
    - README.md
